---

- name: Create user.
  ansible.builtin.user:
    name: test_user
    comment: admin_user_for_service
    group: wheel

- name: Add user to wheel group.
  ansible.builtin.shell:
    cmd: usermod -aG wheel test_user

- name: Create .ssh directory
  ansible.builtin.file:
    path: /home/test_user/.ssh
    state: directory
    mode: '0755'

- name: Create authorized_keys file.
  ansible.builtin.file:
    path: /home/test_user/.ssh/authorized_keys
    state: touch
    mode: '0644'

- name: Copy the pubkey for the user.
  ansible.builtin.copy:
    src: /etc/ansible/roles/forescout_installation/files/test_user_pub_key
    dest: /home/test_user/.ssh/authorized_keys

- name: Open firewall for test user for specific ip.
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 source address=192.168.11.0/24 accept
    permanent: true
    state: enabled

- name: Restart firewalld.
  ansible.builtin.systemd_service:
    name: firewalld
    state: restarted
