---
- hosts: $Specify_Hosts_Here
  tasks:
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /dir to/rpm_file
      dest: /etc/opt
      owner: root
      group: root
      mode: '0777'


  - name: Update rpm from local file.
    ansible.builtin.dnf:
      name: /Location/Of/rpm_file
      state: present
